id: P53064317
initial_creation_type: ocr
source_metadata:
  volumes:
    c9c4282b50084fbaadafba29ae2e2630:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: ''
      total_pages: 1605
      volume_number: 57
